@startwbs plots
+[#Olive] fft \ spect \ time
++[#YellowGreen] task_1
+++[#Gold] FADHD_patient_1_electrode_Cz.png
+++[#Gold] ...
+++[#Gold] FC_patient_9_electrode_Cz.png
+++[#Gold] ...
+++[#Gold] MADHD_patient_14_electrode_F4.png
+++[#Gold] ...
+++[#Gold] MC_patient_29_electrode_F4.png
++[#YellowGreen] task_2
+++[#Gold] ...
++[#YellowGreen] ...
+++[#Gold] ...
++[#YellowGreen] task_11
+++[#Gold] ...
@endwbs